[package]
name = "test"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde_json = "1.0.81"
risc0-zkvm = { version = "2.3.1", default-features = false, features = ['std'] }

[dependencies.serde]
features = ["derive"]
version = "1.0.60"
